# Generated by Django 4.0.6 on 2023-08-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelval', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcqQuestionMaster',
            fields=[
                ('question_aid', models.AutoField(db_column='Question_AID', primary_key=True, serialize=False)),
                ('question_label', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Question_Label', max_length=100)),
                ('section_aid', models.IntegerField(db_column='Section_AID')),
                ('sub_section_aid', models.IntegerField(blank=True, db_column='Sub_Section_AID', null=True)),
                ('sub_sub_section_aid', models.IntegerField(blank=True, db_column='Sub_Sub_Section_AID', null=True)),
                ('sub_sub_sub_section_aid', models.IntegerField(blank=True, db_column='Sub_Sub_Sub_Section_AID', null=True)),
                ('activestatus', models.BooleanField(blank=True, db_column='ActiveStatus', null=True)),
                ('addedby', models.IntegerField(blank=True, db_column='AddedBy', null=True)),
                ('adddate', models.DateTimeField(blank=True, db_column='AddDate', null=True)),
                ('updatedby', models.IntegerField(blank=True, db_column='UpdatedBy', null=True)),
                ('updatedate', models.DateTimeField(blank=True, db_column='UpdateDate', null=True)),
            ],
            options={
                'db_table': 'ICQ_Question_Master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IcqQuestionRating',
            fields=[
                ('rating_id', models.AutoField(db_column='Rating_id', primary_key=True, serialize=False)),
                ('rating_yes', models.IntegerField(blank=True, db_column='Rating_Yes', null=True)),
                ('rating_no', models.IntegerField(blank=True, db_column='Rating_No', null=True)),
                ('doc_yes', models.IntegerField(blank=True, db_column='Doc_Yes', null=True)),
                ('doc_no', models.IntegerField(blank=True, db_column='Doc_No', null=True)),
                ('addedby', models.IntegerField(blank=True, db_column='AddedBy', null=True)),
                ('adddate', models.DateTimeField(blank=True, db_column='AddDate', null=True)),
                ('updatedby', models.IntegerField(blank=True, db_column='UpdatedBy', null=True)),
                ('updatedate', models.DateTimeField(blank=True, db_column='UpdateDate', null=True)),
            ],
            options={
                'db_table': 'ICQ_Question_Rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IcqQuestionRatingAllocation',
            fields=[
                ('allocation_aid', models.AutoField(db_column='Allocation_Aid', primary_key=True, serialize=False)),
                ('review_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Review_id', max_length=10)),
                ('review_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Review_Name', max_length=50)),
                ('section_aid', models.IntegerField(db_column='Section_AID')),
                ('sub_section_aid', models.IntegerField(blank=True, db_column='Sub_Section_AID', null=True)),
                ('sub_sub_section_aid', models.IntegerField(blank=True, db_column='Sub_Sub_Section_AID', null=True)),
                ('sub_sub_sub_section_aid', models.IntegerField(blank=True, db_column='Sub_Sub_Sub_Section_AID', null=True)),
                ('allocated_to', models.IntegerField(db_column='Allocated_to')),
                ('addedby', models.IntegerField(blank=True, db_column='AddedBy', null=True)),
                ('adddate', models.DateTimeField(blank=True, db_column='AddDate', null=True)),
                ('updatedby', models.IntegerField(blank=True, db_column='UpdatedBy', null=True)),
                ('updatedate', models.DateTimeField(blank=True, db_column='UpdateDate', null=True)),
                ('model_id', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Model_Id', max_length=50, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ICQ_Question_Rating_Allocation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IcqSections',
            fields=[
                ('section_aid', models.AutoField(db_column='Section_AID', primary_key=True, serialize=False)),
                ('section_label', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Section_Label', max_length=100)),
                ('activestatus', models.BooleanField(blank=True, db_column='ActiveStatus', null=True)),
                ('addedby', models.IntegerField(blank=True, db_column='AddedBy', null=True)),
                ('adddate', models.DateTimeField(blank=True, db_column='AddDate', null=True)),
                ('updatedby', models.IntegerField(blank=True, db_column='UpdatedBy', null=True)),
                ('updatedate', models.DateTimeField(blank=True, db_column='UpdateDate', null=True)),
                ('section_description', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Section_Description', null=True)),
            ],
            options={
                'db_table': 'ICQ_Sections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IcqSubSections',
            fields=[
                ('sub_section_aid', models.AutoField(db_column='Sub_Section_AID', primary_key=True, serialize=False)),
                ('sub_section_label', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Sub_Section_Label', max_length=100)),
                ('activestatus', models.BooleanField(blank=True, db_column='ActiveStatus', null=True)),
                ('addedby', models.IntegerField(blank=True, db_column='AddedBy', null=True)),
                ('adddate', models.DateTimeField(blank=True, db_column='AddDate', null=True)),
                ('updatedby', models.IntegerField(blank=True, db_column='UpdatedBy', null=True)),
                ('updatedate', models.DateTimeField(blank=True, db_column='UpdateDate', null=True)),
                ('sub_section_description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Sub_Section_Description', max_length=200, null=True)),
            ],
            options={
                'db_table': 'ICQ_Sub_Sections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IcqSubSubSections',
            fields=[
                ('sub_sub_section_aid', models.AutoField(db_column='Sub_Sub_Section_AID', primary_key=True, serialize=False)),
                ('sub_sub_section_label', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Sub_Sub_Section_Label', max_length=100)),
                ('activestatus', models.BooleanField(blank=True, db_column='ActiveStatus', null=True)),
                ('addedby', models.IntegerField(blank=True, db_column='AddedBy', null=True)),
                ('adddate', models.DateTimeField(blank=True, db_column='AddDate', null=True)),
                ('updatedby', models.IntegerField(blank=True, db_column='UpdatedBy', null=True)),
                ('updatedate', models.DateTimeField(blank=True, db_column='UpdateDate', null=True)),
                ('sub_sub_section_description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Sub_Sub_Section_Description', max_length=200, null=True)),
            ],
            options={
                'db_table': 'ICQ_Sub_Sub_Sections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IcqSubSubSubSections',
            fields=[
                ('sub_sub_sub_section_aid', models.AutoField(db_column='Sub_Sub_Sub_Section_AID', primary_key=True, serialize=False)),
                ('sub_sub_sub_section_label', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Sub_Sub_Sub_Section_Label', max_length=100)),
                ('activestatus', models.BooleanField(blank=True, db_column='ActiveStatus', null=True)),
                ('addedby', models.IntegerField(blank=True, db_column='AddedBy', null=True)),
                ('adddate', models.DateTimeField(blank=True, db_column='AddDate', null=True)),
                ('updatedby', models.IntegerField(blank=True, db_column='UpdatedBy', null=True)),
                ('updatedate', models.DateTimeField(blank=True, db_column='UpdateDate', null=True)),
                ('sub_sub_sub_section_description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Sub_Sub_Sub_Section_Description', max_length=200, null=True)),
            ],
            options={
                'db_table': 'ICQ_Sub_Sub_Sub_Sections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationDetails',
            fields=[
                ('notification_id', models.AutoField(db_column='Notification_Id', primary_key=True, serialize=False)),
                ('notification_from', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Notification_From', max_length=250, null=True)),
                ('notification_to', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Notification_To', max_length=250, null=True)),
                ('utility', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Utility', max_length=300, null=True)),
                ('notification_trigger', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Notification_Trigger', max_length=300, null=True)),
                ('is_visible', models.BooleanField(blank=True, db_column='Is_Visible', null=True)),
                ('create_date', models.DateTimeField(blank=True, db_column='Create_Date', null=True)),
            ],
            options={
                'db_table': 'Notification_Details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QueryBuilderFilter',
            fields=[
                ('query_builder_filter_aid', models.AutoField(db_column='Query_Builder_Filter_AID', primary_key=True, serialize=False)),
                ('rule', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Query_Rule', max_length=100)),
                ('addon', models.DateTimeField(blank=True, db_column='AddOn', null=True)),
                ('file_id', models.IntegerField(blank=True, db_column='File_id', null=True)),
                ('addedby', models.IntegerField(blank=True, db_column='AddedBy', null=True)),
                ('rulename', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Rulename', max_length=255, null=True)),
                ('model_id', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Query_Builder_Filter',
                'managed': False,
            },
        ),
    ]
