# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class FlRawData(models.Model):
    fields_aid = models.AutoField(db_column='Fields_AID', primary_key=True)  # Field name made lowercase.
    record_identifier = models.CharField(db_column='Record_Identifier', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    legal_entity_identifier = models.CharField(db_column='Legal_Entity_Identifier', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    universal_loan_identifier_or_non_universal_loan_identifier = models.CharField(db_column='Universal_Loan_Identifier_or_Non_Universal_Loan_Identifier', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    application_date = models.CharField(db_column='Application_Date', max_length=200, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    loan_type = models.CharField(db_column='Loan_Type', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    loan_purpose = models.CharField(db_column='Loan_Purpose', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    preapproval = models.CharField(db_column='Preapproval', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    construction_method = models.CharField(db_column='Construction_Method', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    occupancy_type = models.CharField(db_column='Occupancy_Type', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    loan_amount = models.CharField(db_column='Loan_Amount', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    action_taken = models.CharField(db_column='Action_Taken', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    action_taken_date = models.CharField(db_column='Action_Taken_Date', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    street_address = models.CharField(db_column='Street Address', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    city = models.CharField(db_column='City', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    state = models.CharField(db_column='State', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    zip_code = models.CharField(db_column='ZIP_Code', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    county = models.CharField(db_column='County', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    census_tract = models.CharField(db_column='Census_Tract', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    ethnicity_of_applicant_or_borrower_1 = models.CharField(db_column='Ethnicity_of_Applicant_or_Borrower_1', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    ethnicity_of_applicant_or_borrower_2 = models.CharField(db_column='Ethnicity_of_Applicant_or_Borrower_2', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    ethnicity_of_applicant_or_borrower_3 = models.CharField(db_column='Ethnicity_of_Applicant_or_Borrower_3', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    ethnicity_of_applicant_or_borrower_4 = models.CharField(db_column='Ethnicity_of_Applicant_or_Borrower_4', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    ethnicity_of_applicant_or_borrower_5 = models.CharField(db_column='Ethnicity_of_Applicant_or_Borrower_5', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    ethnicity_of_applicant_or_borrower_free_form_text_field_for_other_hispanic_or_latino = models.CharField(db_column='Ethnicity_of_Applicant_or_Borrower_Free_Form_Text_Field_for_Other_Hispanic_or_Latino', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    ethnicity_of_co_applicant_or_co_borrower_1 = models.CharField(db_column='Ethnicity_of_Co_Applicant_or_Co_Borrower_1', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    ethnicity_of_co_applicant_or_co_borrower_2 = models.CharField(db_column='Ethnicity_of_Co_Applicant_or_Co_Borrower_2', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    ethnicity_of_co_applicant_or_co_borrower_3 = models.CharField(db_column='Ethnicity_of_Co_Applicant_or_Co_Borrower_3', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    ethnicity_of_co_applicant_or_co_borrower_4 = models.CharField(db_column='Ethnicity_of_Co_Applicant_or_Co_Borrower_4', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    ethnicity_of_co_applicant_or_co_borrower_5 = models.CharField(db_column='Ethnicity_of_Co_Applicant_or_Co_Borrower_5', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    ethnicity_of_co_applicant_or_co_borrower_free_form_text_field_for_other_hispanic_or_latino = models.CharField(db_column='Ethnicity_of_Co_Applicant_or_Co_Borrower_Free_Form_Text_Field_for_Other_Hispanic_or_Latino', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    ethnicity_of_applicant_or_borrower_collected_on_the_basis_of_visual_observation_or_surname = models.CharField(db_column='Ethnicity of Applicant or Borrower Collected on the Basis of Visual Observation or Surname', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    ethnicity_of_co_applicant_or_co_borrower_collected_on_the_basis_of_visual_observation_or_surname = models.CharField(db_column='Ethnicity_of_Co_Applicant_or_Co_Borrower_Collected_on_the_Basis_of_Visual_Observation_or_Surname', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    race_of_applicant_or_borrower_1 = models.CharField(db_column='Race_of_Applicant_or_Borrower_1', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    race_of_applicant_or_borrower_2 = models.CharField(db_column='Race_of_Applicant_or_Borrower_2', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    race_of_applicant_or_borrower_3 = models.CharField(db_column='Race_of_Applicant_or_Borrower_3', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    race_of_applicant_or_borrower_4 = models.CharField(db_column='Race_of_Applicant_or_Borrower_4', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    race_of_applicant_or_borrower_5 = models.CharField(db_column='Race_of_Applicant_or_Borrower_5', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    race_of_applicant_or_borrower_free_form_text_field_for_american_indian_or_alaska_native_enrolled_or_principal_tribe = models.CharField(db_column='Race_of_Applicant_or_Borrower_Free_Form_Text_Field_for_American_Indian_or_Alaska_Native_Enrolled_or_Principal_Tribe', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    race_of_applicant_or_borrower_free_form_text_field_for_other_asian = models.CharField(db_column='Race_of_Applicant_or_Borrower_Free_Form_Text_Field_for_Other_Asian', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    race_of_applicant_or_borrower_free_form_text_field_for_other_pacific_islander = models.CharField(db_column='Race_of_Applicant_or_Borrower_Free_Form_Text_Field_for_Other_Pacific_Islander', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    race_of_co_applicant_or_co_borrower_1 = models.CharField(db_column='Race_of_Co_Applicant_or_Co_Borrower_1', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    race_of_co_applicant_or_co_borrower_2 = models.CharField(db_column='Race_of_Co_Applicant_or_Co_Borrower_2', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    race_of_co_applicant_or_co_borrower_3 = models.CharField(db_column='Race_of_Co_Applicant_or_Co_Borrower_3', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    race_of_co_applicant_or_co_borrower_4 = models.CharField(db_column='Race_of_Co_Applicant_or_Co_Borrower_4', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    race_of_co_applicant_or_co_borrower_5 = models.CharField(db_column='Race_of_Co_Applicant_or_Co_Borrower_5', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    race_of_co_applicant_or_co_borrower_free_form_text_field_for_american_indian_or_alaska_native_enrolled_or_principal_tribe = models.CharField(db_column='Race_of_Co_Applicant_or_Co_Borrower_Free_Form_Text_Field_for_American_Indian_or_Alaska_Native_Enrolled_or_Principal_Tribe', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    race_of_co_applicant_or_co_borrower_free_form_text_field_for_other_asian = models.CharField(db_column='Race_of_Co_Applicant_or_Co_Borrower_Free_Form_Text_Field_for_Other_Asian', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    race_of_co_applicant_or_co_borrower_free_form_text_field_for_other_pacific_islander = models.CharField(db_column='Race_of_Co_Applicant_or_Co_Borrower_Free_Form_Text_Field_for_Other_Pacific_Islander', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    race_of_applicant_or_borrower_collected_on_the_basis_of_visual_observation_or_surname = models.CharField(db_column='Race_of_Applicant_or_Borrower_Collected_on_the_Basis_of_Visual_Observation_or_Surname', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    race_of_co_applicant_or_co_borrower_collected_on_the_basis_of_visual_observation_or_surname = models.CharField(db_column='Race_of_Co_Applicant_or_Co_Borrower_Collected_on_the_Basis_of_Visual_Observation_or_Surname', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    sex_of_applicant_or_borrower = models.CharField(db_column='Sex_of_Applicant_or_Borrower', max_length=255, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    sex_of_co_applicant_or_co_borrower = models.CharField(db_column='Sex_of_Co_Applicant_or_Co_Borrower', max_length=255, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    sex_of_applicant_or_borrower_collected_on_the_basis_of_visual_observation_or_surname = models.CharField(db_column='Sex_of_Applicant_or_Borrower_Collected_on_the_Basis_of_Visual_Observation_or_Surname', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    sex_of_co_applicant_or_co_borrower_collected_on_the_basis_of_visual_observation_or_surname = models.CharField(db_column='Sex_of_Co_Applicant_or_Co_Borrower_Collected_on_the_Basis_of_Visual_Observation_or_Surname', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    age_of_applicant_or_borrower = models.CharField(db_column='Age_of_Applicant_or_Borrower', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    age_of_co_applicant_or_co_borrower = models.CharField(db_column='Age of Co-Applicant or Co-Borrower', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    income = models.CharField(db_column='Income', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    type_of_purchaser = models.CharField(db_column='Type_of_Purchaser', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    rate_spread = models.CharField(db_column='Rate_Spread', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    hoepa_status = models.CharField(db_column='HOEPA_Status', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    lien_status = models.CharField(db_column='Lien_Status', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    credit_score_of_applicant_or_borrower = models.CharField(db_column='Credit_Score_of_Applicant_or_Borrower', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    credit_score_of_co_applicant_or_co_borrower = models.CharField(db_column='Credit_Score_of_Co_Applicant_or_Co_Borrower', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    applicant_or_borrower_name_and_version_of_credit_scoring_model = models.CharField(db_column='Applicant_or_Borrower_Name_and_Version_of_Credit_Scoring_Model', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    applicant_or_borrower_name_and_version_of_credit_scoring_model_conditional_free_form_text_field_for_code_8 = models.CharField(db_column='Applicant_or_Borrower_Name_and_Version_of_Credit_Scoring_Model_Conditional_Free_Form_Text_Field_for_Code_8', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    co_applicant_or_co_borrower_name_and_version_of_credit_scoring_model = models.CharField(db_column='Co_Applicant_or_Co_Borrower_Name_and_Version_of_Credit_Scoring_Model', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    co_applicant_or_co_borrower_name_and_version_of_credit_scoring_model_conditional_free_form_text_field_for_code_8 = models.CharField(db_column='Co_Applicant_or_Co_Borrower_Name_and_Version_of_Credit_Scoring_Model_Conditional_Free_Form_Text_Field_for_Code_8', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    reason_for_denial_1 = models.CharField(db_column='Reason_for_Denial_1', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    reason_for_denial_2 = models.CharField(db_column='Reason_for_Denial_2', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    reason_for_denial_3 = models.CharField(db_column='Reason_for_Denial_3', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    reason_for_denial_4 = models.CharField(db_column='Reason_for_Denial_4', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    reason_for_denial_conditional_free_form_text_field_for_code_9 = models.CharField(db_column='Reason_for_Denial_Conditional_Free_Form_Text_Field_for_Code_9', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    total_loan_costs = models.CharField(db_column='Total_Loan_Costs', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    total_points_and_fees = models.CharField(db_column='Total_Points_and_Fees', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    origination_charges = models.CharField(db_column='Origination_Charges', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    discount_points = models.CharField(db_column='Discount_Points', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    lender_credits = models.CharField(db_column='Lender_Credits', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    interest_rate = models.CharField(db_column='Interest_Rate', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    prepayment_penalty_term = models.CharField(db_column='Prepayment_Penalty_Term', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    debt_to_income_ratio = models.CharField(db_column='Debt_to_Income_Ratio', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    combined_loan_to_value_ratio = models.CharField(db_column='Combined_Loan_to_Value_Ratio', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    loan_term = models.CharField(db_column='Loan_Term', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    introductory_rate_period = models.CharField(db_column='Introductory_Rate_Period', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    balloon_payment = models.CharField(db_column='Balloon_Payment', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    interest_only_payments = models.CharField(db_column='Interest_Only_Payments', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    negative_amortization = models.CharField(db_column='Negative_Amortization', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    other_non_amortizing_features = models.CharField(db_column='Other_Non_Amortizing_Features', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    property_value = models.CharField(db_column='Property_Value', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    manufactured_home_secured_property_type = models.CharField(db_column='Manufactured_Home_Secured_Property_Type', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    manufactured_home_land_property_interest = models.CharField(db_column='Manufactured_Home_Land_Property_Interest', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    total_units = models.CharField(db_column='Total_Units', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    multifamily_affordable_units = models.CharField(db_column='Multifamily_Affordable_Units', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    submission_of_application = models.CharField(db_column='Submission_of_Application', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    initially_payable_to_your_institution = models.CharField(db_column='Initially_Payable_to_Your_Institution', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    mortgage_loan_originator_nmlsr_identifier = models.CharField(db_column='Mortgage_Loan_Originator_NMLSR_Identifier', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    automated_underwriting_system_1 = models.CharField(db_column='Automated_Underwriting_System_1', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    automated_underwriting_system_2 = models.CharField(db_column='Automated_Underwriting_System_2', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    automated_underwriting_system_3 = models.CharField(db_column='Automated_Underwriting_System_3', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    automated_underwriting_system_4 = models.CharField(db_column='Automated_Underwriting_System_4', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    automated_underwriting_system_5 = models.CharField(db_column='Automated_Underwriting_System_5', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    automated_underwriting_system_conditional_free_form_text_field_for_code_5 = models.CharField(db_column='Automated_Underwriting_System_Conditional_Free_Form_Text_Field_for_Code_5', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    automated_underwriting_system_result_1 = models.CharField(db_column='Automated_Underwriting_System_Result_1', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    automated_underwriting_system_result_2 = models.CharField(db_column='Automated_Underwriting_System_Result_2', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    automated_underwriting_system_result_3 = models.CharField(db_column='Automated_Underwriting_System_Result_3', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    automated_underwriting_system_result_4 = models.CharField(db_column='Automated_Underwriting_System_Result_4', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    automated_underwriting_system_result_5 = models.CharField(db_column='Automated_Underwriting_System_Result_5', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    automated_underwriting_system_result_conditional_free_form_text_field_for_code_16 = models.CharField(db_column='Automated_Underwriting_System_Result_Conditional_Free_Form_Text_Field_for_Code_16', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    reverse_mortgage = models.CharField(db_column='Reverse_Mortgage', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    open_end_line_of_credit = models.CharField(db_column='Open_End_Line_of_Credit', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    business_or_commercial_purpose = models.CharField(db_column='Business_or_Commercial_Purpose', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    addedby = models.IntegerField(db_column='AddedBy', blank=True, null=True)  # Field name made lowercase.
    adddate = models.DateTimeField(db_column='AddDate', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'FL_RAW_DATA'
