# Generated by Django 4.0.6 on 2023-10-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTrail',
            fields=[
                ('activity_aid', models.AutoField(db_column='Activity_AID', primary_key=True, serialize=False)),
                ('refference_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Refference_Id', max_length=200)),
                ('activity_trigger', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Activity_Trigger', max_length=200, null=True)),
                ('activity_details', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Activity_Details', max_length=200, null=True)),
                ('addedby', models.IntegerField(blank=True, db_column='AddedBy', null=True)),
                ('added_on', models.DateTimeField(blank=True, db_column='Added_On', null=True)),
            ],
            options={
                'db_table': 'Activity_Trail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditRegComplAllocation',
            fields=[
                ('allocation_aid', models.AutoField(db_column='Allocation_AID', primary_key=True, serialize=False)),
                ('compl_aid', models.IntegerField(db_column='Compl_AID')),
                ('mdl_id', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Mdl_Id', max_length=50, null=True)),
                ('addedby', models.IntegerField(blank=True, null=True)),
                ('addedon', models.DateTimeField(blank=True, null=True)),
                ('allocated_to', models.IntegerField(blank=True, db_column='Allocated_to', null=True)),
            ],
            options={
                'db_table': 'Audit_Reg_Compl_Allocation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditRegComplResp',
            fields=[
                ('compl_resp_aid', models.AutoField(db_column='Compl_Resp_AID', primary_key=True, serialize=False)),
                ('compl_aid', models.IntegerField(db_column='Compl_AID')),
                ('mdl_id', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Mdl_Id', max_length=50, null=True)),
                ('question_resp', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Question_Resp', max_length=500, null=True)),
                ('addedby', models.IntegerField(blank=True, null=True)),
                ('addedon', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Audit_Reg_Compl_Resp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MdlRelevantPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdl_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Mdl_Id', max_length=20)),
                ('u_type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='U_Type', max_length=20, null=True)),
                ('u_id', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='U_ID', max_length=2, null=True)),
                ('addedby', models.IntegerField(blank=True, db_column='AddedBy', null=True)),
                ('adddate', models.DateTimeField(blank=True, db_column='AddDate', null=True)),
                ('updatedby', models.IntegerField(blank=True, db_column='UpdatedBy', null=True)),
                ('updatedate', models.DateTimeField(blank=True, db_column='UpdateDate', null=True)),
            ],
            options={
                'db_table': 'Mdl_Relevant_personnel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelOverview',
            fields=[
                ('mdl_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Mdl_Id', max_length=20, primary_key=True, serialize=False)),
                ('mdl_cnt', models.IntegerField(db_column='Mdl_Cnt')),
                ('mdl_major_ver', models.IntegerField(db_column='Mdl_Major_Ver')),
                ('mdl_minor_ver', models.IntegerField(db_column='Mdl_Minor_Ver')),
                ('isnewupdate', models.BooleanField(blank=True, null=True)),
                ('is_tool', models.BooleanField(blank=True, null=True)),
                ('department', models.IntegerField(db_column='Department')),
                ('func', models.IntegerField(db_column='Func')),
                ('reg_dt', models.DateTimeField(blank=True, db_column='Reg_Dt', null=True)),
                ('prm_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Prm_Name', max_length=200)),
                ('sec_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Sec_Name', max_length=200, null=True)),
                ('mdl_source', models.IntegerField(db_column='Mdl_Source')),
                ('mdl_type', models.IntegerField(db_column='Mdl_Type')),
                ('mdl_absct', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Mdl_Absct', max_length=200, null=True)),
                ('mdl_objective', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Mdl_objective', max_length=200, null=True)),
                ('mdl_appl', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Mdl_Appl', max_length=200, null=True)),
                ('mdl_risk_anls', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Mdl_Risk_Anls', max_length=200, null=True)),
                ('prctaddr', models.IntegerField(db_column='PrctAddr')),
                ('usgfreq', models.IntegerField(db_column='UsgFreq')),
                ('addedby', models.IntegerField(blank=True, db_column='AddedBy', null=True)),
                ('adddate', models.DateTimeField(blank=True, db_column='AddDate', null=True)),
                ('updatedby', models.IntegerField(blank=True, db_column='UpdatedBy', null=True)),
                ('updatedate', models.DateTimeField(blank=True, db_column='UpdateDate', null=True)),
            ],
            options={
                'db_table': 'Mdl_OverView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolesResponsibilityQuestionAllocation',
            fields=[
                ('question_allocation_aid', models.AutoField(db_column='Question_Allocation_AID', primary_key=True, serialize=False)),
                ('qtn_aid', models.IntegerField(db_column='Qtn_AID')),
                ('mdl_id', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Mdl_Id', max_length=50, null=True)),
                ('addedby', models.IntegerField(blank=True, null=True)),
                ('addedon', models.DateTimeField(blank=True, null=True)),
                ('allocated_to', models.IntegerField(blank=True, db_column='Allocated_to', null=True)),
            ],
            options={
                'db_table': 'Roles_Responsibility_Question_Allocation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolesResponsibilityQuestionResponse',
            fields=[
                ('question_response_aid', models.AutoField(db_column='Question_Response_AID', primary_key=True, serialize=False)),
                ('qtn_aid', models.IntegerField(db_column='Qtn_AID')),
                ('mdl_id', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Mdl_Id', max_length=50, null=True)),
                ('qtn_resp', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Qtn_Resp', max_length=50, null=True)),
                ('addedby', models.IntegerField(blank=True, null=True)),
                ('addedon', models.DateTimeField(blank=True, null=True)),
                ('allocated_to', models.IntegerField(blank=True, db_column='Allocated_to', null=True)),
            ],
            options={
                'db_table': 'Roles_Responsibility_Question_Response',
                'managed': False,
            },
        ),
    ]
